### PR TITLE
Add badges from pypi

### LINKED ISSUE #932: Update (correct) docs about python version support for `python>=3.7`
The `pyproject.toml` file says that python version support is for `python>=3.7`.

https://github.com/scikit-rf/scikit-rf/blob/c6e85afb771197d0e4a1f2b7bbfe7612f3694c3a/pyproject.toml#L5

However, the [documentation](https://scikit-rf.org/install.html) has stale (misleading) information, as shown below. Please correct the docs.

image

## Investigated the Root Cause

I tried looking for the source and the closest match that I found is this:

https://github.com/scikit-rf/scikit-rf/blob/c6e85afb771197d0e4a1f2b7bbfe7612f3694c3a/doc/source/tutorials/Installation.ipynb#L13.

But to me it seems like the website is no longer getting any latest updates from this repository. If that is the case, please either setup auto updates using CI/CD, or take it down: https://scikit-rf.org/install.html.

### PR DESCRIPTION
**Pull request by FranzForstmayr**
Should fix https://github.com/scikit-rf/scikit-rf/issues/932

### CODE REVIEW

**Comment by FranzForstmayr** [comment]
When https://github.com/scikit-rf/scikit-rf/pull/944 is merged and released, the supported Python versions should be displayed correctly.

**Comment by FranzForstmayr** [comment]
Currently it looks like this:
PyPI - Python Version

Should look like (stolen from numpy):
PyPI - Python Version

**Review by jhillairet — APPROVED** [review]

**Comment by FranzForstmayr** [comment]
@jhillairet I think we can merge this.

**Comment by jhillairet** [comment]
Right, I forgot. Thanks.

**Comment by FranzForstmayr** [comment]
Can you deploy the new website please?

**Comment by jhillairet** [comment]
I will, when I'll be @ home

**Pull request merged**
